/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import useInterval from '../../utils/timer'



export function Logo(props) {
  const { nodes, materials } = useGLTF('/girinlogo.glb')
  let [intensity, setIntensity] = useState(0)

  let timer = useInterval(() => {
    if (localStorage.getItem('accessToken') != null ) {
      setIntensity(intensity + 0.01)
      clearInterval(timer)
      console.log('hi' + intensity)}
    else {
    }
    }
  , 60, 6240)
  
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} receiveShadow castShadow >
      <meshStandardMaterial attach="material" emissive={'lightblue'} emissiveIntensity={intensity} color="lightblue" roughness={0} metalness={0.3} />
      </mesh>
      <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} receiveShadow castShadow>
      <meshStandardMaterial attach="material" emissive={'lightblue'} emissiveIntensity={intensity} color="lightblue" roughness={0} metalness={0.3} />
      </mesh>
      <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} receiveShadow castShadow>
      <meshStandardMaterial attach="material" color="lightgray" roughness={0} metalness={0.5} />
      </mesh>
      <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} receiveShadow castShadow>
      <meshStandardMaterial attach="material" color="lightgray" roughness={0} metalness={0.5} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/girinlogo.glb')
